name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "VITE_SOKCET_URL=${{ secrets.VITE_SOKCET_URL }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Build project
        run: npm run build

      - name: Set up Git authentication
        run: |
          git config --global user.email "bilalzaim499@gmail.com"
          git config --global user.name "Bilal-EZ-ZAIM"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Bilal-EZ-ZAIM/moride-front-end.git

      - name: Deploy to GitHub Pages
        run: npm run deploy
